apiVersion: v1
kind: Pod
metadata:
  name: data-retrieval-osm
spec:
  restartPolicy: Never
  securityContext:
    runAsUser: 71032 #248465
    runAsGroup: 9915
  volumes:
    - name: geograd
      nfs:
        server: 128.239.59.144
        path: /sciclone/geograd
  containers:
    - name: conda-container
      image: "condaforge/mambaforge"
      resources:
        requests:
          ephemeral-storage: "10Gi"
          memory: "32Gi"
          cpu: "4"
      volumeMounts:
        - name: geograd
          mountPath: /sciclone/geograd/
      command: ["/bin/bash", "-c"]
      args:
        - |
          source /sciclone/geograd/_deployed/globalRoads/_venv/bin/activate
          #python /kube/home/git/globalRoads/sourceData/retrieveData.py
          sleep 99999